
/**********************************************************************
*
*   Component generated by Quest
*
*   WARNING: By editing this component by hand, you will lose the ability to regenerate the code without conflicts. 
*   To preseve that abilty, always export from Quest to regenerate this file.
*   To setup props, bindings and actions, use the Quest editor
*   Code Logic goes in the hook associated with this component
*
*   For help and further details refer to: https://www.quest.ai/docs
*
*
**********************************************************************/

import React from 'react';
import Group77Image from 'src/assets/images/AirBnbExperiences_Group_77.png';
import Rectangle13Image from 'src/assets/images/AirBnbExperiences_Rectangle_13.png';
import VectorImage from 'src/assets/images/AirBnbExperiences_Vector.png';
import Star1Image from 'src/assets/images/AirBnbExperiences_Star_1_2.png';
import Ellipse6Image from 'src/assets/images/AirBnbExperiences_Ellipse_6_2.png';
import Star11Image from 'src/assets/images/AirBnbExperiences_Star_1_1.png';
import Ellipse61Image from 'src/assets/images/AirBnbExperiences_Ellipse_6_1.png';
import Star12Image from 'src/assets/images/AirBnbExperiences_Star_1.png';
import Ellipse62Image from 'src/assets/images/AirBnbExperiences_Ellipse_6.png';
import Image12Image from 'src/assets/images/AirBnbExperiences_image_12.png';
import WeddingPhotography1Image from 'src/assets/images/AirBnbExperiences_wedding_photography_1.png';
import MountainBike1Image from 'src/assets/images/AirBnbExperiences_mountain_bike_1.png';
import { styled } from '@mui/material/styles';

 
const AirBnbExperiences1 = styled("div")({  
  backgroundColor: `rgba(255, 255, 255, 1)`,  
  borderRadius: `8.949999809265137px`,  
  display: `flex`,  
  position: `relative`,  
  isolation: `isolate`,  
  flexDirection: `row`,  
  width: "100%",  
  height: `853px`,  
  justifyContent: `flex-start`,  
  alignItems: `flex-start`,  
  padding: `0px`,  
  boxSizing: `border-box`,  
  overflow: `hidden`,  
});
  
const Group77 = styled("img")({  
  height: `232px`,  
  width: `395.91px`,  
  position: `absolute`,  
  left: `77px`,  
  top: `96px`,  
});
  
const Rectangle13 = styled("img")({  
  height: `70px`,  
  width: `550px`,  
  position: `absolute`,  
  left: `0px`,  
  top: `0px`,  
});
  
const Airbnb1 = styled("div")({  
  display: `flex`,  
  position: `absolute`,  
  isolation: `isolate`,  
  flexDirection: `row`,  
  justifyContent: `flex-start`,  
  alignItems: `flex-start`,  
  padding: `0px`,  
  boxSizing: `border-box`,  
  width: `82.02px`,  
  height: `25.35px`,  
  left: `30px`,  
  top: `22px`,  
  overflow: `hidden`,  
});
  
const Vector = styled("img")({  
  height: `25.35px`,  
  width: `82px`,  
  position: `absolute`,  
  left: `0px`,  
  top: `0px`,  
});
  
const OnlineExperiences = styled("div")({  
  textAlign: `left`,  
  whiteSpace: `pre-wrap`,  
  color: `rgba(0, 0, 0, 1)`,  
  fontStyle: `normal`,  
  fontFamily: `Poppins`,  
  fontWeight: `600`,  
  fontSize: `36px`,  
  letterSpacing: `0px`,  
  textDecoration: `none`,  
  lineHeight: `110.00000238418579%`,  
  textTransform: `none`,  
  width: `347px`,  
  position: `absolute`,  
  left: `36px`,  
  top: `360px`,  
});
  
const JoinUniqueInteractiv = styled("div")({  
  textAlign: `left`,  
  whiteSpace: `pre-wrap`,  
  color: `rgba(34, 34, 34, 1)`,  
  fontStyle: `normal`,  
  fontFamily: `Poppins`,  
  fontWeight: `300`,  
  fontSize: `16px`,  
  letterSpacing: `0px`,  
  textDecoration: `none`,  
  lineHeight: `110.00000238418579%`,  
  textTransform: `none`,  
  width: `320px`,  
  height: `56px`,  
  position: `absolute`,  
  left: `36px`,  
  top: `416px`,  
});
  
const Group65 = styled("div")({  
  display: `flex`,  
  position: `absolute`,  
  isolation: `isolate`,  
  flexDirection: `row`,  
  justifyContent: `flex-start`,  
  alignItems: `flex-start`,  
  padding: `0px`,  
  boxSizing: `border-box`,  
  width: `176px`,  
  height: `58px`,  
  left: `36px`,  
  top: `765px`,  
});
  
const LifeLessonsWithKatie = styled("div")({  
  textAlign: `left`,  
  whiteSpace: `pre-wrap`,  
  color: `rgba(34, 34, 34, 1)`,  
  fontStyle: `normal`,  
  fontFamily: `Poppins`,  
  fontWeight: `300`,  
  fontSize: `12px`,  
  letterSpacing: `0px`,  
  textDecoration: `none`,  
  lineHeight: `110.00000238418579%`,  
  textTransform: `none`,  
  width: `175px`,  
  height: `14px`,  
  position: `absolute`,  
  left: `1px`,  
  top: `22px`,  
});
  
const From136PersonSpan1 = styled("span")({  
  whiteSpace: `pre-wrap`,  
  color: `rgba(34, 34, 34, 1)`,  
  fontStyle: `normal`,  
  fontFamily: `Poppins`,  
  fontWeight: `600`,  
  fontSize: `12px`,  
  letterSpacing: `0px`,  
  textDecoration: `none`,  
  lineHeight: `110.00000238418579%`,  
  textTransform: `none`,  
});
  
const From136PersonSpan2 = styled("span")({  
  whiteSpace: `pre-wrap`,  
  color: `rgba(34, 34, 34, 1)`,  
  fontStyle: `normal`,  
  fontFamily: `Poppins`,  
  fontWeight: `300`,  
  fontSize: `12px`,  
  letterSpacing: `0px`,  
  textDecoration: `none`,  
  lineHeight: `110.00000238418579%`,  
  textTransform: `none`,  
});
  
const From136Person = styled("div")({  
  textAlign: `left`,  
  whiteSpace: `pre-wrap`,  
  color: `rgba(34, 34, 34, 1)`,  
  fontStyle: `normal`,  
  fontFamily: "unset",  
  fontWeight: `400`,  
  fontSize: `12px`,  
  letterSpacing: `0px`,  
  textDecoration: `none`,  
  lineHeight: `110.00000238418579%`,  
  textTransform: `none`,  
  width: `144px`,  
  height: `14px`,  
  position: `absolute`,  
  left: `0px`,  
  top: `44px`,  
});
  
const Q50 = styled("div")({  
  textAlign: `left`,  
  whiteSpace: `pre-wrap`,  
  color: `rgba(34, 34, 34, 1)`,  
  fontStyle: `normal`,  
  fontFamily: `Poppins`,  
  fontWeight: `300`,  
  fontSize: `12px`,  
  letterSpacing: `0px`,  
  textDecoration: `none`,  
  lineHeight: `110.00000238418579%`,  
  textTransform: `none`,  
  width: `18px`,  
  height: `14px`,  
  position: `absolute`,  
  left: `16px`,  
  top: `0px`,  
});
  
const Q6 = styled("div")({  
  textAlign: `left`,  
  whiteSpace: `pre-wrap`,  
  color: `rgba(145, 142, 155, 1)`,  
  fontStyle: `normal`,  
  fontFamily: `Poppins`,  
  fontWeight: `300`,  
  fontSize: `12px`,  
  letterSpacing: `0px`,  
  textDecoration: `none`,  
  lineHeight: `110.00000238418579%`,  
  textTransform: `none`,  
  width: `18px`,  
  height: `14px`,  
  position: `absolute`,  
  left: `36px`,  
  top: `0px`,  
});
  
const Usa = styled("div")({  
  textAlign: `left`,  
  whiteSpace: `pre-wrap`,  
  color: `rgba(145, 142, 155, 1)`,  
  fontStyle: `normal`,  
  fontFamily: `Poppins`,  
  fontWeight: `300`,  
  fontSize: `12px`,  
  letterSpacing: `0px`,  
  textDecoration: `none`,  
  lineHeight: `110.00000238418579%`,  
  textTransform: `none`,  
  width: `23px`,  
  height: `14px`,  
  position: `absolute`,  
  left: `60px`,  
  top: `0px`,  
});
  
const Star1 = styled("img")({  
  height: `14px`,  
  width: `14px`,  
  position: `absolute`,  
  left: `0px`,  
  top: `0px`,  
});
  
const Ellipse6 = styled("img")({  
  height: `2px`,  
  width: `2px`,  
  position: `absolute`,  
  left: `56px`,  
  top: `6px`,  
});
  
const Group78 = styled("div")({  
  display: `flex`,  
  position: `absolute`,  
  isolation: `isolate`,  
  flexDirection: `row`,  
  justifyContent: `flex-start`,  
  alignItems: `flex-start`,  
  padding: `0px`,  
  boxSizing: `border-box`,  
  width: `176px`,  
  height: `58px`,  
  left: `230px`,  
  top: `765px`,  
});
  
const LearnWeddingPhotogra = styled("div")({  
  textAlign: `left`,  
  whiteSpace: `pre-wrap`,  
  color: `rgba(34, 34, 34, 1)`,  
  fontStyle: `normal`,  
  fontFamily: `Poppins`,  
  fontWeight: `300`,  
  fontSize: `12px`,  
  letterSpacing: `0px`,  
  textDecoration: `none`,  
  lineHeight: `110.00000238418579%`,  
  textTransform: `none`,  
  width: `175px`,  
  height: `14px`,  
  position: `absolute`,  
  left: `1px`,  
  top: `22px`,  
});
  
const From125PersonSpan1 = styled("span")({  
  whiteSpace: `pre-wrap`,  
  color: `rgba(34, 34, 34, 1)`,  
  fontStyle: `normal`,  
  fontFamily: `Poppins`,  
  fontWeight: `600`,  
  fontSize: `12px`,  
  letterSpacing: `0px`,  
  textDecoration: `none`,  
  lineHeight: `110.00000238418579%`,  
  textTransform: `none`,  
});
  
const From125PersonSpan2 = styled("span")({  
  whiteSpace: `pre-wrap`,  
  color: `rgba(34, 34, 34, 1)`,  
  fontStyle: `normal`,  
  fontFamily: `Poppins`,  
  fontWeight: `300`,  
  fontSize: `12px`,  
  letterSpacing: `0px`,  
  textDecoration: `none`,  
  lineHeight: `110.00000238418579%`,  
  textTransform: `none`,  
});
  
const From125Person = styled("div")({  
  textAlign: `left`,  
  whiteSpace: `pre-wrap`,  
  color: `rgba(34, 34, 34, 1)`,  
  fontStyle: `normal`,  
  fontFamily: "unset",  
  fontWeight: `400`,  
  fontSize: `12px`,  
  letterSpacing: `0px`,  
  textDecoration: `none`,  
  lineHeight: `110.00000238418579%`,  
  textTransform: `none`,  
  width: `144px`,  
  height: `14px`,  
  position: `absolute`,  
  left: `0px`,  
  top: `44px`,  
});
  
const Q501 = styled("div")({  
  textAlign: `left`,  
  whiteSpace: `pre-wrap`,  
  color: `rgba(34, 34, 34, 1)`,  
  fontStyle: `normal`,  
  fontFamily: `Poppins`,  
  fontWeight: `300`,  
  fontSize: `12px`,  
  letterSpacing: `0px`,  
  textDecoration: `none`,  
  lineHeight: `110.00000238418579%`,  
  textTransform: `none`,  
  width: `18px`,  
  height: `14px`,  
  position: `absolute`,  
  left: `16px`,  
  top: `0px`,  
});
  
const Q30 = styled("div")({  
  textAlign: `left`,  
  whiteSpace: `pre-wrap`,  
  color: `rgba(145, 142, 155, 1)`,  
  fontStyle: `normal`,  
  fontFamily: `Poppins`,  
  fontWeight: `300`,  
  fontSize: `12px`,  
  letterSpacing: `0px`,  
  textDecoration: `none`,  
  lineHeight: `110.00000238418579%`,  
  textTransform: `none`,  
  width: `27px`,  
  height: `18px`,  
  position: `absolute`,  
  left: `36px`,  
  top: `0px`,  
});
  
const Usa1 = styled("div")({  
  textAlign: `left`,  
  whiteSpace: `pre-wrap`,  
  color: `rgba(145, 142, 155, 1)`,  
  fontStyle: `normal`,  
  fontFamily: `Poppins`,  
  fontWeight: `300`,  
  fontSize: `12px`,  
  letterSpacing: `0px`,  
  textDecoration: `none`,  
  lineHeight: `110.00000238418579%`,  
  textTransform: `none`,  
  width: `23px`,  
  height: `14px`,  
  position: `absolute`,  
  left: `70px`,  
  top: `0px`,  
});
  
const Star11 = styled("img")({  
  height: `14px`,  
  width: `14px`,  
  position: `absolute`,  
  left: `0px`,  
  top: `0px`,  
});
  
const Ellipse61 = styled("img")({  
  height: `2px`,  
  width: `2px`,  
  position: `absolute`,  
  left: `64px`,  
  top: `6px`,  
});
  
const Group79 = styled("div")({  
  display: `flex`,  
  position: `absolute`,  
  isolation: `isolate`,  
  flexDirection: `row`,  
  justifyContent: `flex-start`,  
  alignItems: `flex-start`,  
  padding: `0px`,  
  boxSizing: `border-box`,  
  width: `176px`,  
  height: `58px`,  
  left: `424px`,  
  top: `765px`,  
});
  
const GroupMountainBiking = styled("div")({  
  textAlign: `left`,  
  whiteSpace: `pre-wrap`,  
  color: `rgba(34, 34, 34, 1)`,  
  fontStyle: `normal`,  
  fontFamily: `Poppins`,  
  fontWeight: `300`,  
  fontSize: `12px`,  
  letterSpacing: `0px`,  
  textDecoration: `none`,  
  lineHeight: `110.00000238418579%`,  
  textTransform: `none`,  
  width: `175px`,  
  height: `14px`,  
  position: `absolute`,  
  left: `1px`,  
  top: `22px`,  
});
  
const From50PersonSpan1 = styled("span")({  
  whiteSpace: `pre-wrap`,  
  color: `rgba(34, 34, 34, 1)`,  
  fontStyle: `normal`,  
  fontFamily: `Poppins`,  
  fontWeight: `600`,  
  fontSize: `12px`,  
  letterSpacing: `0px`,  
  textDecoration: `none`,  
  lineHeight: `110.00000238418579%`,  
  textTransform: `none`,  
});
  
const From50PersonSpan2 = styled("span")({  
  whiteSpace: `pre-wrap`,  
  color: `rgba(34, 34, 34, 1)`,  
  fontStyle: `normal`,  
  fontFamily: `Poppins`,  
  fontWeight: `300`,  
  fontSize: `12px`,  
  letterSpacing: `0px`,  
  textDecoration: `none`,  
  lineHeight: `110.00000238418579%`,  
  textTransform: `none`,  
});
  
const From50Person = styled("div")({  
  textAlign: `left`,  
  whiteSpace: `pre-wrap`,  
  color: `rgba(34, 34, 34, 1)`,  
  fontStyle: `normal`,  
  fontFamily: "unset",  
  fontWeight: `400`,  
  fontSize: `12px`,  
  letterSpacing: `0px`,  
  textDecoration: `none`,  
  lineHeight: `110.00000238418579%`,  
  textTransform: `none`,  
  width: `144px`,  
  height: `14px`,  
  position: `absolute`,  
  left: `0px`,  
  top: `44px`,  
});
  
const Q48 = styled("div")({  
  textAlign: `left`,  
  whiteSpace: `pre-wrap`,  
  color: `rgba(34, 34, 34, 1)`,  
  fontStyle: `normal`,  
  fontFamily: `Poppins`,  
  fontWeight: `300`,  
  fontSize: `12px`,  
  letterSpacing: `0px`,  
  textDecoration: `none`,  
  lineHeight: `110.00000238418579%`,  
  textTransform: `none`,  
  width: `18px`,  
  height: `14px`,  
  position: `absolute`,  
  left: `16px`,  
  top: `0px`,  
});
  
const Q2 = styled("div")({  
  textAlign: `left`,  
  whiteSpace: `pre-wrap`,  
  color: `rgba(145, 142, 155, 1)`,  
  fontStyle: `normal`,  
  fontFamily: `Poppins`,  
  fontWeight: `300`,  
  fontSize: `12px`,  
  letterSpacing: `0px`,  
  textDecoration: `none`,  
  lineHeight: `110.00000238418579%`,  
  textTransform: `none`,  
  width: `18px`,  
  height: `14px`,  
  position: `absolute`,  
  left: `36px`,  
  top: `0px`,  
});
  
const Usa2 = styled("div")({  
  textAlign: `left`,  
  whiteSpace: `pre-wrap`,  
  color: `rgba(145, 142, 155, 1)`,  
  fontStyle: `normal`,  
  fontFamily: `Poppins`,  
  fontWeight: `300`,  
  fontSize: `12px`,  
  letterSpacing: `0px`,  
  textDecoration: `none`,  
  lineHeight: `110.00000238418579%`,  
  textTransform: `none`,  
  width: `23px`,  
  height: `14px`,  
  position: `absolute`,  
  left: `60px`,  
  top: `0px`,  
});
  
const Star12 = styled("img")({  
  height: `14px`,  
  width: `14px`,  
  position: `absolute`,  
  left: `0px`,  
  top: `0px`,  
});
  
const Ellipse62 = styled("img")({  
  height: `2px`,  
  width: `2px`,  
  position: `absolute`,  
  left: `56px`,  
  top: `6px`,  
});
  
const Image12 = styled("img")({  
  height: `235px`,  
  width: `176px`,  
  objectFit: `cover`,  
  position: `absolute`,  
  left: `37px`,  
  top: `521px`,  
});
  
const Group80 = styled("div")({  
  display: `flex`,  
  position: `absolute`,  
  isolation: `isolate`,  
  flexDirection: `row`,  
  justifyContent: `flex-start`,  
  alignItems: `flex-start`,  
  padding: `0px`,  
  boxSizing: `border-box`,  
  width: `61px`,  
  height: `20px`,  
  left: `43px`,  
  top: `527px`,  
});
  
const Rectangle41 = styled("div")({  
  backgroundColor: `rgba(255, 255, 255, 1)`,  
  borderRadius: `2px`,  
  width: `61px`,  
  height: `20px`,  
  position: `absolute`,  
  left: `0px`,  
  top: `0px`,  
});
  
const SoldOut = styled("div")({  
  textAlign: `center`,  
  whiteSpace: `pre-wrap`,  
  color: `rgba(34, 34, 34, 1)`,  
  fontStyle: `normal`,  
  fontFamily: `Poppins`,  
  fontWeight: `400`,  
  fontSize: `10.239999771118164px`,  
  letterSpacing: `0px`,  
  textDecoration: `none`,  
  lineHeight: `110.00000238418579%`,  
  textTransform: `none`,  
  position: `absolute`,  
  left: `6px`,  
  top: `5px`,  
});
  
const Group72 = styled("div")({  
  display: `flex`,  
  position: `absolute`,  
  isolation: `isolate`,  
  flexDirection: `row`,  
  justifyContent: `flex-start`,  
  alignItems: `flex-start`,  
  padding: `0px`,  
  boxSizing: `border-box`,  
  width: `160px`,  
  height: `40px`,  
  left: `239px`,  
  top: `705px`,  
});
  
const FurtherDescriptionsA = styled("div")({  
  textAlign: `left`,  
  whiteSpace: `pre-wrap`,  
  color: `rgba(255, 255, 255, 1)`,  
  fontStyle: `normal`,  
  fontFamily: `Poppins`,  
  fontWeight: `300`,  
  fontSize: `12px`,  
  letterSpacing: `0px`,  
  textDecoration: `none`,  
  lineHeight: `120.00000476837158%`,  
  textTransform: `none`,  
  width: `160px`,  
  height: `40px`,  
  position: `absolute`,  
  left: `0px`,  
  top: `0px`,  
});
  
const WeddingPhotography1 = styled("img")({  
  height: `235px`,  
  width: `176px`,  
  position: `absolute`,  
  left: `231px`,  
  top: `521px`,  
});
  
const MountainBike1 = styled("img")({  
  height: `235px`,  
  width: `176px`,  
  position: `absolute`,  
  left: `425px`,  
  top: `521px`,  
});
  
const Group81 = styled("div")({  
  display: `flex`,  
  position: `absolute`,  
  isolation: `isolate`,  
  flexDirection: `row`,  
  justifyContent: `flex-start`,  
  alignItems: `flex-start`,  
  padding: `0px`,  
  boxSizing: `border-box`,  
  width: `61px`,  
  height: `20px`,  
  left: `239px`,  
  top: `527px`,  
});
  
const Rectangle411 = styled("div")({  
  backgroundColor: `rgba(255, 255, 255, 1)`,  
  borderRadius: `2px`,  
  width: `61px`,  
  height: `20px`,  
  position: `absolute`,  
  left: `0px`,  
  top: `0px`,  
});
  
const Online = styled("div")({  
  textAlign: `center`,  
  whiteSpace: `pre-wrap`,  
  color: `rgba(34, 34, 34, 1)`,  
  fontStyle: `normal`,  
  fontFamily: `Poppins`,  
  fontWeight: `400`,  
  fontSize: `10.239999771118164px`,  
  letterSpacing: `0px`,  
  textDecoration: `none`,  
  lineHeight: `110.00000238418579%`,  
  textTransform: `none`,  
  position: `absolute`,  
  left: `13px`,  
  top: `5px`,  
});
 
function AirBnbExperiences(props) {
  
    return (
    <AirBnbExperiences1  className={props.className}   >
      <Group77  src={Group77Image} alt={"Group 77"}/>
      <Rectangle13  src={Rectangle13Image} alt={"Rectangle 13"}/>
      <Airbnb1 >
        <Vector  src={VectorImage} alt={"Vector"}/>
      </Airbnb1>
      <OnlineExperiences >
        {`Online Experiences`}
          </OnlineExperiences>
      <JoinUniqueInteractiv >
        {`Join unique interactive activities led by one-of-a-kind hosts—all without leaving home.
`}
          </JoinUniqueInteractiv>
      <Group65 >
        <LifeLessonsWithKatie >
          {`Life lessons with Katie Zaferes
`}
            </LifeLessonsWithKatie>
        <From136Person >
          <From136PersonSpan1  >{`From $136 `}</From136PersonSpan1>
          <From136PersonSpan2  >{`/ person
`}</From136PersonSpan2>
        </From136Person>
        <Q50 >
          {`5.0
`}
            </Q50>
        <Q6 >
          {`(6)`}
            </Q6>
        <Usa >
          {`USA`}
            </Usa>
        <Star1  src={Star1Image} alt={"Star 1"}/>
        <Ellipse6  src={Ellipse6Image} alt={"Ellipse 6"}/>
      </Group65>
      <Group78 >
        <LearnWeddingPhotogra >
          {`Learn wedding photography
`}
            </LearnWeddingPhotogra>
        <From125Person >
          <From125PersonSpan1  >{`From $125 `}</From125PersonSpan1>
          <From125PersonSpan2  >{`/ person
`}</From125PersonSpan2>
        </From125Person>
        <Q501 >
          {`5.0
`}
            </Q501>
        <Q30 >
          {`(30)`}
            </Q30>
        <Usa1 >
          {`USA`}
            </Usa1>
        <Star11  src={Star11Image} alt={"Star 1"}/>
        <Ellipse61  src={Ellipse61Image} alt={"Ellipse 6"}/>
      </Group78>
      <Group79 >
        <GroupMountainBiking >
          {`Group Mountain Biking`}
            </GroupMountainBiking>
        <From50Person >
          <From50PersonSpan1  >{`From $50 `}</From50PersonSpan1>
          <From50PersonSpan2  >{`/ person
`}</From50PersonSpan2>
        </From50Person>
        <Q48 >
          {`4.8`}
            </Q48>
        <Q2 >
          {`(2)`}
            </Q2>
        <Usa2 >
          {`USA`}
            </Usa2>
        <Star12  src={Star12Image} alt={"Star 1"}/>
        <Ellipse62  src={Ellipse62Image} alt={"Ellipse 6"}/>
      </Group79>
      <Image12  src={Image12Image} alt={"image 12"}/>
      <Group80 >
        <Rectangle41 >
        </Rectangle41>
        <SoldOut >
          {`SOLD OUT`}
            </SoldOut>
      </Group80>
      <Group72 >
        <FurtherDescriptionsA >
          {`Further descriptions about Life lessons with Katie Zaferes
`}
            </FurtherDescriptionsA>
      </Group72>
      <WeddingPhotography1  src={WeddingPhotography1Image} alt={"wedding-photography 1"}/>
      <MountainBike1  src={MountainBike1Image} alt={"mountain-bike 1"}/>
      <Group81 >
        <Rectangle411 >
        </Rectangle411>
        <Online >
          {`ONLINE`}
            </Online>
      </Group81>
    </AirBnbExperiences1>
  );
}

export default AirBnbExperiences;
